window.local = true;
window.plierpoint=1;
window.plierpoly=9999;
window.plierline=999;
window.verbose = false;
window.dev = false;
window.solrhost = "http://solr-lbones.rhcloud.com/";
window.queryinit = "chupacabr*";
// window.solrhost = "http://localhost:8983/solr/";