# My variables
name: Spatial Track
description: a mapped blog about mappable music

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "templates"]
baseurl: "http://map.milleria.org"

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Outputting
permalink:     pretty

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge